import { pxToRem } from './functions'

/**
 * Object defining breakpoints for different devices.
 * Values are defined in `pixels`.
 */
const breakpoints = {
  mobile: 576,
  tablet: 768,
  notebook: 992,
  desktop: 1200,
}

/**
 * Type generated by the keys in the object `breakpoints`.
 */
type DeviceType = keyof typeof breakpoints

/**
 * Generates a `media query` in `rem` for devices with a maximum width `below`
 * the specified breakpoint.
 *
 * @param device The breakpoint for the generated media query.
 * @returns {string} A string containing the media query.
 *
 * @example
 * const styles = css`
 * ${below('desktop')} {
 *  // Styles for smaller devices than "desktop" breakpoint
 * }
 * `
 */
export function below(device: DeviceType): string {
  return `@media (max-width: ${pxToRem(breakpoints[device])})`
}

/**
 * Generates a `media query` in `rem` for devices with a minimum width `above`
 * the specified breakpoint.
 *
 * @param device The breakpoint for the generated media query.
 * @returns {string} A string containing the media query.
 *
 * @example
 * const styles = css`
 * ${above('tablet')} {
 *  // Styles for larger devices than "tablet" breakpoint
 * }
 * `
 */
export function above(device: DeviceType): string {
  return `@media (min-width: ${pxToRem(breakpoints[device])})`
}

/**
 * Generates a custom media query for different screen sizes.
 * Automatic converts pixels to rem (base 16px).
 *
 * @param screen The properties for screen sizes: 'max-width' for `below` and
 * 'min-width' for `above`.
 * @param pixels The number in pixels that will be automatic converted by rem.
 * Base 16px.
 * @returns {string} A string containing the custom media query.
 *
 * @example
 * const styles = css`
 * ${media('max-width' or 'min-width', 400)} {
 *  // Styles here...
 * }
 * `
 */
export function media(
  screen: 'max-width' | 'min-width',
  pixels: number,
): string {
  return `@media (${screen}:${pxToRem(pixels)})`
}
